---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Reiya24/learn-devtron.git
    targetRevision: HEAD
    path: my-app
  destination:
    server: https://kubernetes.default.svc